#TODO public credentials, no problem to show it

# WARNING - don't ever encrypt passwords when storing them at a database
#16 BYTES
encryption:
  algorithm: AES
  key: 2f#k*28FG9%d&829

#jwt manual security token
jwt:
  clocksec: 400
  expirationsec: 86400
  issuer: fenixcommunity
  secret: d)kfd&2kfff

#aws credentials from spring cloud vault
#aws:
#  app:
#    keyid :  xxx
#    secretkey :  xxx

#restcaller
restcaller:
  credentials:
    password: password
    username: BASIC_USER
